name : test
on: push 


jobs:
  cypress:
    runs-on: ubuntu-latest

    steps:
      - name: setup
        uses: actions/checkout@v2

      - name: setup
        run: yarn
      - name: setup
        run: yarn start &
      - name: setup
        run: yarn naosei