name : test
on: push


jobs:
  cypress:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
    
      - name: Install packages
        run: npm i
        run: npm start &
        run: npm naosei